language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install sphinx
install:
  - pip install pytest flaky -r requirements.txt
script:
  - py.test -s -v --cov=convoys .
  - sphinx-build -M html docs/ docs/_build/
after_success:
  - coveralls
