language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install pytest -r requirements.txt
script:
  - py.test --cov=convoys .
after_success:
  - coveralls
